-- TEAMS 
CREATE OR REPLACE TRIGGER TEAM_ID_EDITOR 
BEFORE INSERT
   ON TEAMS
   FOR EACH ROW
DECLARE 
   n        NUMBER(3);
   max_id   NUMBER(7);
BEGIN
   SELECT COUNT(*)
   INTO n FROM TEAMS 
   WHERE department_id = :new.department_id;
   IF n = 0 THEN
      :new.team_id := :new.department_id * 1000 + 1;
      RETURN;
   END IF;

   SELECT max(team_id)
   INTO max_id FROM TEAMS 
   WHERE department_id = :new.department_id;

   :new.team_id := max_id + 1;
END;
/


-- MEDICAL_EXAMINATIONS
DROP SEQUENCE MEDICAL_EX_SEQUENCE;
CREATE SEQUENCE MEDICAL_EX_SEQUENCE minvalue 0;

CREATE OR REPLACE TRIGGER MEDICAL_EX_AUTOINCR
BEFORE INSERT
   ON MEDICAL_EXAMINATIONS
   FOR EACH ROW
BEGIN
     :new.med_id := MEDICAL_EX_SEQUENCE.NextVal;
END;
/



-- INSPECTION
DROP SEQUENCE INSPECTION_SEQUENCE;
CREATE SEQUENCE INSPECTION_SEQUENCE minvalue 0;

CREATE OR REPLACE TRIGGER INSPECTION_AUTOINCR
BEFORE INSERT
   ON INSPECTIONS
   FOR EACH ROW
BEGIN
     :new.inspection_id := INSPECTION_SEQUENCE.NextVal;
END;
/


-- PATHS
DROP SEQUENCE PATH_SEQUENCE;
CREATE SEQUENCE PATH_SEQUENCE minvalue 0;

CREATE OR REPLACE  TRIGGER PATH_AUTOINCR
BEFORE INSERT
   ON PATHS
   FOR EACH ROW
BEGIN
     :new.path_id := PATH_SEQUENCE.NextVal;
END;
/
   

